sonar.projectKey=naruto-backend

sonar.projectName=Naruto Backend

sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.login=sqa_82c38246c9bd296a39166cb04988e3d33603fa0d

sonar.java.binaries=target/classes