sonar.projectKey=dragonball-backend

sonar.projectName=DragonBall Backend

sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.exclusions=venv/**,__pycache__/**

sonar.host.url=http://localhost:9000

sonar.login=sqa_82c38246c9bd296a39166cb04988e3d33603fa0d